# Permalinks
permalink:           pretty

# Setup
title:               Stefan Ruijsenaars
tagline:             Blog 
url:                 https://www.stefanruijsenaars.com/blog
paginate:            1
baseurl:             "https://www.stefanruijsenaars.com"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Stefan Ruijsenaars
  url:               https://twitter.com/stefan_arrr
  email:             stefan@doxxo.nl

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/stefanruijsenaars

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-twitter-plugin

